### ISSUE TITLE
It adds currency symbol after the value, but i want before value, Is it possible ?

### ISSUE THREAD

**Issue by pj210493** [PaXLiCh/FormattEditText#3]

**Comment by PaXLiCh** [comment]
It just formats currency edit text with your specified locale and currency settings. With some locales same currency symbol can be placed before or after the value. If you want to specify position of some character, you need to find correct locale, or use the DecimalEditText with plurals (each plural must contain currency simbol) or use MaskedEditText with mask, which will contain your currency symbol at any place.
