### ISSUE TITLE
Migrate to Androidx

### ISSUE THREAD

**Issue by Shusshu** [PaXLiCh/FormattEditText#5]
Could you migrate the lib from support.android to androidx?

**Comment by PaXLiCh** [comment]
at the moment there is absolutely no time to work on the project, probably much later I will try to migrate for androidx.

**Comment by Shusshu** [comment]
I see you started it - did you finish?

**Comment by PaXLiCh** [comment]
As there will be free time, I will publish an update. A little patience. Thank you for your interest.

**Comment by Shusshu** [comment]
Hey could you release then new version to bintray or maven repo?

**Comment by PaXLiCh** [comment]
within a couple of days the release will be.

**Comment by PaXLiCh** [comment]
version 0.8 with androidx.appcompat:appcompat:1.1.0 available now.

**Comment by Shusshu** [comment]
thanks!
