### ISSUE TITLE
duplicate value for resource 'attr/placeholder' with config ''.

### ISSUE THREAD

**Issue by moeindev** [PaXLiCh/FormattEditText#6]
Hey!
I get this error at compile time:

> /Users/myUser/.gradle/caches/transforms-2/files-2.1/a4437a932490e83b8af1eb320ceab6c6/jetified-formatt-edit-text-0.7/res/values/values.xml:5:5-143: AAPT: error: duplicate value for resource 'attr/placeholder' with config ''.

**Comment by PaXLiCh** [comment]
Maybe conflicting modules or incorrect gradle configuration.
